# Cylane config file via .yaml

bot:
  TOKEN: Your token
  EMBED_COLOR: "Your color. Example: #ffffff"
  OWNER_ID: "Your id"

  # Realtime now playing bar
  NP_REALTIME: false
  LEAVE_TIMEOUT: 100
  LANGUAGE: en

  # Your id or friend id (disable global command)
  DEV_ID: []

  # Your mongo_uri, you can get it from here: https://www.mongodb.com/
  MONGO_URI: mongodb://127.0.0.1:27017/dreamvast

  ENABLE_MESSAGE: false
  AUTO_DEPLOY: true
  PREFIX: "d!"

  # Use alive server for replit
  ALIVE_SERVER: true
  ALIVE_SERVER_PORT: 3000
  # DASHBOARD: false

lavalink:
  # Your spotify id and secret, you can get it from here: https://developer.spotify.com/
  # If you don't have or don't want, you can disable it
  ENABLE_SPOTIFY: false
  SPOTIFY_ID: Your spotify id
  SPOTIFY_SECRET: Your spotify secret

  DEFAULT: ["yorushika", "yoasobi", "tuyu", "hinkik"]

  # Enable this if you want to use lavalink info from .env files
  ENV_NODE: false
  
  # You can add more lavalink server!
  NODES: [
    {
      url: lava1.horizxon.studio:80,
      name: Node_1,
      auth: horizxon.studio,
      secure: false,
    },
  ]
  SHOUKAKU_OPTIONS: {
    moveOnDisconnect: true,
    resumable: true,
    resumableTimeout: 600,
    reconnectTries: Infinity,
    restTimeout: 3000
  }


websocket:
  PORT: 8080
  WEBSOCKET: true
  # If you enable authenicator, you have to put your origin link to TRUSTED_ORIGIN
  AUTHENICATOR: true
  TRUSTED_ORIGIN: ['http://localhost:3000']

# dash:
#   PORT: 3000
#   # If you change the PORT, you have to change this to! Ex: `PORT: 9999, DISCORD_REDIRECT_URL: http://localhost:9999/api/auth/discord/redirect`
#   REDIRECT: http://localhost:3000/menu
#   SIGNATURE: cylane/a69c29e2f989c7d06f98b6e462c835a4 # Type anything you want
#   # Discord Auth App
#   DISCORD_CLIENT_ID: "Your bot id"
#   DISCORD_CLIENT_SECRET: "Your bot secret"
  
#   # You have to add the redirect url in your discord developer portal, remove the <>
#   # Link: https://discord.com/developers/applications/<your_bot_id>/oauth2/general
#   # If you change the PORT, you have to change this to! Ex: `PORT: 9999, DISCORD_REDIRECT_URL: http://localhost:9999/api/auth/discord/redirect`
#   DISCORD_REDIRECT_URL: http://localhost:3000/api/auth/discord/redirect 
#   DISCORD_API_URL: https://discord.com/api/v10
#   # If you use https, you have to enable SECURE
#   SECURE: false