# Cylane config file via .yaml

bot:
  TOKEN: Your token
  EMBED_COLOR: "Your color. Example: #ffffff"
  OWNER_ID: "Your id"
  LANGUAGE: en # You can set it to vi, en, th,...
  LIMIT_TRACK: 50 # The number of tracks you want to limit
  LIMIT_PLAYLIST: 20 # The number of playlist you want to limit
  # Your mongo_uri, you can get it from here: https://www.mongodb.com/
  MONGO_URI: mongodb://127.0.0.1:27017/dreamvast

lavalink:

  SPOTIFY:
    # Your spotify id and secret, you can get it from here: https://developer.spotify.com/
    # If you don't have or don't want, you can disable it
    enable: true
    id: a98a98s9a89as98a9s8a98
    secret: a98a98s9a89as98a9s8a98

  DEFAULT: ["yorushika", "yoasobi", "tuyu", "hinkik"]
  
  ENV_NODE: false # Enable this if you want to use lavalink info from .env files
  NP_REALTIME: false # Enable this if you want to use realtime duation in nowplaying command

  LEAVE_TIMEOUT: 100 # The number of leave time you want

  # You can add more lavalink server!
  NODES: [
    {
      url: "narco.buses.rocks:2269",
      name: "Node_1",
      auth: "glasshost1984",
      secure: false,
    },
  ]
  SHOUKAKU_OPTIONS: {
    moveOnDisconnect: true,
    resumable: true,
    resumableTimeout: 600,
    reconnectTries: Infinity,
    restTimeout: 3000
  }

features:
  LOCAL_DATABASE:
    enable: false
    path: "./cylane.database.json" # Database file path
  
  SHARD_SYSTEM: 
    enable: false # If you want to use shard system, change it to `true`
    totalShards: 3 # you can set to every number you want but for save mode, use 'auto' option
    totalClusters: 1 # you can set to every number you want but for save mode, use 'auto' option
    shardsPerClusters: 2
    mode: 'worker' # you can also choose "process"

  MESSAGE_CONTENT:
    enable: true
    prefix: "d!" # The prefix you want
  
  AUTO_DEPLOY: true
  AUTO_REMOVE_DUPLICATE: true

  ALIVE_SERVER:
    enable: false
    port: 3000

  WEBSOCKET:
    enable: true
    port: 8080
    auth: true
    trusted: ['http://localhost:3000']

  # Your id or friend id (disable global command)
  DEV_ID: []

# dash:
#   PORT: 3000
#   # If you change the PORT, you have to change this to! Ex: `PORT: 9999, DISCORD_REDIRECT_URL: http://localhost:9999/api/auth/discord/redirect`
#   REDIRECT: http://localhost:3000/menu
#   SIGNATURE: cylane/a69c29e2f989c7d06f98b6e462c835a4 # Type anything you want
#   # Discord Auth App
#   DISCORD_CLIENT_ID: "Your bot id"
#   DISCORD_CLIENT_SECRET: "Your bot secret"
  
#   # You have to add the redirect url in your discord developer portal, remove the <>
#   # Link: https://discord.com/developers/applications/<your_bot_id>/oauth2/general
#   # If you change the PORT, you have to change this to! Ex: `PORT: 9999, DISCORD_REDIRECT_URL: http://localhost:9999/api/auth/discord/redirect`
#   DISCORD_REDIRECT_URL: http://localhost:3000/api/auth/discord/redirect 
#   DISCORD_API_URL: https://discord.com/api/v10
#   # If you use https, you have to enable SECURE
#   SECURE: false